name: "fta-cli"

description: "Runs FTA and comments a diff of the analysis on a PR"

inputs:
  base_sha:
    description: "Sha of the base"
    required: true
  pr_sha:
    description: "Sha of the PR"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout base commit
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.base_sha }}

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install -g yarn
        npm install -g ts-node
        yarn

    - name: Run fta-cli against the base
      shell: bash
      run: |
        cd ${{ github.action_path }}
        ls -l
        ts-node baseRun.ts

    - name: Checkout PR commit
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.pr_sha }}

    - name: Run fta-cli against the PR
      shell: bash
      run: ts-node ${{ github.action_path }}/prRun.ts

    - name: Comment on the PR
      shell: bash
      run: ts-node ${{ github.action_path }}/comment.ts
