name: "fta-cli"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fta-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npm install -g ts-node

      - name: Run fta-cli against the base
        id: base
        run: ts-node ./scripts/baseRun.ts

      - name: Checkout PR commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run fta-cli against the PR
        id: pr
        run: ts-node ./scripts/prRun.ts

      - name: Comment on the PR
        run: ts-node ./scripts/comment.ts
